import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link  from 'next/Link'
import styles from '../styles/Home.module.css'


const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      {/* Login Page Header  */}
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Green side of the page */}

      <div className="container">
        <h1> Statify </h1>
          <style jsx>{`
            .container {
              margin: 50px;
            }
          `}</style>
      </div>

      

      {/* Log in side of page */}
      <div>
        {/* login button */}
        <button type="button" className = "loginbutton"> 
          <Link href={'/home'}>
            <h1 className = "loginfont"> login 
              <style jsx>{`
                .loginfont {

                  position: absolute;
                  width: 434px;
                  height: 47px;
                  left: 720px;
                  top: 640px;
                  background: #2FE3B8;

                  font-family: 'Pacifico', cursive;
                  font-style: normal;
                  font-weight: 400;
                  font-size: 24px;
                  line-height: 38px;

                  color: #000000;            
                }
              `}</style>
            </h1>
          </Link>
        </button>
      </div>


      <main className={styles.main}>
        <h1 className={styles.title}>
          {/* this is how you create new pages =>*/}
          Welcome to <a href="/home">Next.js!</a>
        </h1>
      </main>
    </div>
  )
}

export default Home
