
import type { NextPage } from "next";
import Head from "next/head";
import LoginBox from "../components/LoginBox";
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <div className="login-page">
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div className="login-grid ">
        {/* Login Page Header  */}
        <div className="stats-grid">
          <div className="text-center container-stats">
            <Image src="/spotifyLogo.png" width={100} height={100}></Image>
            {/* Green side of the page */}
            <div>
              <h1 className="home-title">Statify</h1>
              <h2 className="home-subtitle">
                Please login using your spotify credentials to see your Spotify
                Stats!
              </h2>
            </div>
          </div>
        </div>
        <div>
          {/* Log in side of page */}
          <div className="loginbox-grid">
            {/* login button */}
            <LoginBox />
          </div>
        </div>
      </div>
    </div>
  );
};

export default Home;
